# Generated by Django 5.1.15 on 2026-01-26 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('target_month', models.DateField(help_text='计划针对的月份')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_locked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ForecastEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggested_qty', models.DecimalField(decimal_places=2, help_text='MRP 建议生产量', max_digits=10)),
                ('eta_date', models.DateField(help_text='目标入库日期 (满足需求的时间)')),
                ('suggested_start_date', models.DateField(help_text='建议开工日期 (ETA - LeadTime)')),
                ('calculation_note', models.CharField(blank=True, max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
                ('production_order', models.OneToOneField(blank=True, help_text='关联的生产工单', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forecast_source', to='production.productionorder')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='forecast.forecastplan')),
            ],
            options={
                'ordering': ['suggested_start_date'],
            },
        ),
        migrations.CreateModel(
            name='MarketDemand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_date', models.DateField(help_text='需求月份 (通常存为该月1号)')),
                ('country', models.CharField(db_index=True, max_length=50)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('demand_type', models.CharField(choices=[('FORECAST', 'Sales Forecast'), ('ACTUAL', 'Actual Sales')], db_index=True, default='FORECAST', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(limit_choices_to={'nature': 'FG'}, on_delete=django.db.models.deletion.CASCADE, related_name='market_demands', to='inventory.product')),
            ],
            options={
                'verbose_name': 'Market Demand',
                'indexes': [models.Index(fields=['period_date', 'product'], name='forecast_ma_period__e10415_idx')],
                'unique_together': {('period_date', 'country', 'product', 'demand_type')},
            },
        ),
    ]
