# Generated by Django 5.1.15 on 2026-01-26 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketdemand',
            name='is_allocated',
            field=models.BooleanField(default=False, help_text='[Actual Only] Stock has been reserved/allocated for this demand.'),
        ),
    ]
