# Generated by Django 5.1.15 on 2026-01-27 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0002_marketdemand_is_allocated'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketdemand',
            name='shipped_date',
            field=models.DateField(blank=True, help_text='实际出仓日期 (填写后代表库存已扣除)', null=True),
        ),
    ]
