# Generated by Django 5.1.15 on 2026-01-27 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0003_marketdemand_shipped_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketdemand',
            name='allocated_qty',
            field=models.DecimalField(decimal_places=2, default=0, help_text='已锁定的库存数量 (Reserved Stock)', max_digits=10),
        ),
    ]
