# Generated by Django 5.1.15 on 2026-01-28 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0004_marketdemand_allocated_qty'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutboundShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(help_text='Container No. or Booking Ref', max_length=50, unique=True)),
                ('etd', models.DateField(help_text='Estimated Time of Departure')),
                ('status', models.CharField(choices=[('PLANNING', 'Planning'), ('SHIPPED', 'Shipped'), ('ARRIVED', 'Arrived')], default='PLANNING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='marketdemand',
            name='shipment',
            field=models.ForeignKey(blank=True, help_text='所属的出货柜/批次', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demands', to='forecast.outboundshipment'),
        ),
    ]
