# Generated by Django 5.1.15 on 2026-01-28 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0005_outboundshipment_marketdemand_shipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='outboundshipment',
            name='destination',
            field=models.CharField(blank=True, help_text='Optional: Restrict this shipment to a specific Country/Customer.', max_length=50, null=True),
        ),
    ]
