# Generated by Django 5.1.15 on 2026-01-28 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0006_outboundshipment_destination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecastentry',
            name='calculation_note',
            field=models.TextField(blank=True, help_text='存储详细的 MRP 计算逻辑 (JSON)'),
        ),
    ]
