# Generated by Django 5.1.15 on 2026-01-19 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(db_index=True, help_text='物料编码 (SKU)', max_length=50, unique=True)),
                ('description', models.CharField(blank=True, help_text='物料描述', max_length=255)),
                ('uom', models.CharField(default='EA', help_text='单位 (Unit of Measure)', max_length=10)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, help_text='成本价', max_digits=10)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('safety_stock_days', models.IntegerField(default=14, help_text='目标安全库存天数')),
                ('moq', models.DecimalField(decimal_places=2, default=0, help_text='最小起订量 (MOQ)', max_digits=10)),
                ('lead_time_days', models.IntegerField(default=30, help_text='采购/生产前置时间 (Lead Time)')),
                ('nature', models.CharField(choices=[('RAW', 'Ingredient / Raw Material'), ('PKG', 'Packaging Material'), ('FG', 'Finished Product')], db_index=True, default='FG', max_length=10, verbose_name='Product Nature')),
                ('category', models.CharField(db_index=True, default='General', help_text='e.g. Syrups, Sauces, Purees', max_length=50)),
                ('unit_weight', models.DecimalField(decimal_places=2, default=0, help_text='Unit Weight (kg)', max_digits=10)),
                ('unit_volume', models.DecimalField(decimal_places=2, default=0, help_text='单品体积 (L)', max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature', models.CharField(choices=[('RAW', 'Ingredient / Raw Material'), ('PKG', 'Packaging Material'), ('FG', 'Finished Product')], db_index=True, max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('contact_person', models.CharField(blank=True, help_text='联系人', max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='FinishedGoods',
            fields=[
            ],
            options={
                'verbose_name': 'Finished Good',
                'verbose_name_plural': 'Finished Goods',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('inventory.product',),
        ),
        migrations.CreateModel(
            name='PackagingMaterial',
            fields=[
            ],
            options={
                'verbose_name': 'Packaging Material',
                'verbose_name_plural': 'Packaging Materials',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('inventory.product',),
        ),
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
            ],
            options={
                'verbose_name': 'Raw Material',
                'verbose_name_plural': 'Raw Materials',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('inventory.product',),
        ),
        migrations.AddField(
            model_name='product',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventory.productgroup'),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='供应商', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventory.supplier'),
        ),
        migrations.CreateModel(
            name='InventorySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(help_text='数据快照日期 (通常是导入当天)')),
                ('quantity_on_hand', models.DecimalField(decimal_places=2, help_text='现有库存 (SOH)', max_digits=12)),
                ('quantity_on_order', models.DecimalField(decimal_places=2, default=0, help_text='在途库存 (PO Issued)', max_digits=12)),
                ('quantity_reserved', models.DecimalField(decimal_places=2, default=0, help_text='已预留库存 (Reserved)', max_digits=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='inventory.product')),
            ],
            options={
                'ordering': ['-snapshot_date'],
                'indexes': [models.Index(fields=['snapshot_date', 'product'], name='inventory_i_snapsho_96db8a_idx')],
                'unique_together': {('product', 'snapshot_date')},
            },
        ),
        migrations.CreateModel(
            name='ProductAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias_name', models.CharField(db_index=True, max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='inventory.product')),
            ],
            options={
                'unique_together': {('product', 'alias_name')},
            },
        ),
    ]
