# Generated by Django 5.1.15 on 2026-01-19 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_temporary',
            field=models.BooleanField(default=False, help_text='是否为导入时因数据冲突产生的临时产品'),
        ),
    ]
