# Generated by Django 5.1.15 on 2026-01-20 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_is_temporary'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillOfMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, default=1, help_text='Qty required to make 1 unit of FG', max_digits=10)),
                ('component', models.ForeignKey(limit_choices_to=models.Q(('nature', 'FG'), _negated=True), on_delete=django.db.models.deletion.CASCADE, related_name='used_in_boms', to='inventory.product', verbose_name='Component')),
                ('product', models.ForeignKey(limit_choices_to={'nature': 'FG'}, on_delete=django.db.models.deletion.CASCADE, related_name='bom_lines', to='inventory.product', verbose_name='Finished Good')),
            ],
            options={
                'verbose_name': 'Bill of Material',
                'verbose_name_plural': 'Bill of Materials',
                'unique_together': {('product', 'component')},
            },
        ),
    ]
