services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    # Overrides Dockerfile CMD to use dev server
    command: python manage.py runserver 0.0.0.0:7749
    volumes:
      - ./src:/app             # Hot reloading
      - static_volume:/vol/web/static
      - media_volume:/vol/web/media
    ports:
      - "7749:7749"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # REFACTORED: Now uses variables from your .env file
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    healthcheck:
      # Updated to use the variable so it matches the actual user
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    restart: always

volumes:
  postgres_data:
  static_volume:
  media_volume:
