upstream django {
    server app:7749;
}

# Block 1: Redirect HTTP (80) to HTTPS (443)
server {
    listen 80;
    server_name kwanyee.online www.kwanyee.online;

    location / {
        return 301 https://$host$request_uri;
    }
}

# Block 2: Handle HTTPS (443)
server {
    listen 443 ssl;
    server_name kwanyee.online www.kwanyee.online;

    # SSL Certificates (Must match the volume mount in docker-compose)
    ssl_certificate /etc/nginx/certs/fullchain.pem;
    ssl_certificate_key /etc/nginx/certs/privkey.pem;

    # Basic SSL Security Settings
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    # Serve Static Files
    location /static/ {
        alias /vol/web/static/;
    }

    # Serve Media Files
    location /media/ {
        alias /vol/web/media/;
    }

    # Pass everything else to Django
    location / {
        proxy_pass              http://django;
        proxy_set_header        Host $host;
        proxy_set_header        X-Real-IP $remote_addr;
        proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header        X-Forwarded-Proto $scheme;
    }
}
