# Generated by Django 5.1.15 on 2026-02-25 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Chloe Koo', max_length=100)),
                ('title', models.CharField(default='Supply Chain Transformation & Automation Specialist | Practical Python Problem Solver', max_length=200)),
                ('location', models.CharField(default='Malaysia, Kuala Lumpur', max_length=100)),
                ('phone', models.CharField(default='+60 17-638 7638', max_length=50)),
                ('email', models.EmailField(default='kwanyee.koo@gmail.com', max_length=254)),
                ('professional_profile', models.TextField(default='A supply chain enthusiast and self-taught developer specializing in bridging the gap between complex business operations and technical automation...')),
                ('manifesto_intro', models.TextField(default='I am not a commercial software engineer by trade; I am an operations specialist who mastered Python as a strategic tool to eliminate inefficiency...')),
                ('manifesto_reason', models.TextField(default='After successfully transforming logistics operations and automating myself out of daily repetitive tasks, I am seeking to exit my current comfort zone...')),
            ],
        ),
    ]
