# Generated by Django 5.1.15 on 2026-02-25 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeprofile',
            name='edu_quote',
            field=models.TextField(default='"Pivoted from traditional academia to pursue a high-intensity, practice-based self-driven learning path. This background provided a rigorous foundation in financial logic and data integrity. I do not carry a formal degree, but I carry a portfolio of solved problems and live systems. I define my value not by credentials, but by my capability to learn rapidly and deliver tangible business results."'),
        ),
        migrations.AddField(
            model_name='resumeprofile',
            name='edu_subtitle',
            field=models.CharField(default='Completed 6 months of Foundation and 2 years of Professional Degree coursework.', max_length=200),
        ),
        migrations.AddField(
            model_name='resumeprofile',
            name='edu_title',
            field=models.CharField(default='Academic Background in Accounting & Finance', max_length=200),
        ),
        migrations.CreateModel(
            name='Competency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencies', to='core.resumeprofile')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date_range', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=200)),
                ('is_current', models.BooleanField(default=False)),
                ('bullets', models.TextField(help_text='Separate bullets with a newline')),
                ('order', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='core.resumeprofile')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
